### ISSUE TITLE
Font file not loading: user_bf_36.png (user_ardu_36.png works, but user_bf_36.png doesn't)

### ISSUE THREAD

**Issue by davenewt** [avsaase/walksnail-osd-tool#28]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Software version

0.2.0 (20230423.211732)

### What operating system are you using?

Ventura 13.2

### What GPU are you using?

M2 Max

### What problem did you encounter?

Thank you for this tool! I've just tried it, and found that the user_bf_36.png font file doesn't load when dropped onto the GUI. The user_ardu_36.png font file does work OK, however.

**Comment by avsaase** [comment]
Can you share the font file so I can take a look?

**Comment by davenewt** [comment]
Sure, it's this one... 
![user_bf_36](https://github.com/avsaase/walksnail-osd-tool/assets/2853647/c1c33e6b-30bf-416e-b0da-6aa78335a485)

**Comment by avsaase** [comment]
This is fixed in 9338c2122cd8b97566c75d2cc3f50868563741d0. You can download a dev build with the fix from https://nightly.link/avsaase/walksnail-osd-tool/workflows/release.yaml/master/walksnail-osd-tool-all-platforms.zip.

**Comment by davenewt** [comment]
Hmm, I just downloaded the latest release today, and dropping the "user_ardu_36.png" font file works, but when I drop the "user_bf_36.png" file onto the UI, the "Font file" option goes blank and no preview is displayed. Has something else changed? I dragged the above file back out to test in case there was a diff, but still no dice. Still getting the blank "Font file" option (second screenshot attached).

![Screenshot 2023-08-02 at 12 48 38](https://github.com/avsaase/walksnail-osd-tool/assets/2853647/4e7496ff-e131-4c06-a6a2-7fb43ec40323)

![Screenshot 2023-08-02 at 12 48 48](https://github.com/avsaase/walksnail-osd-tool/assets/2853647/2140304b-2189-4fdd-a568-f3c071a641d0)
